name: water_pumps
channels:
  - mosek
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - ampl-mp=3.1.0
  - arviz=0.11.2
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cftime=1.5.1.1
  - colorama=0.4.4
  - cppad=20210000.6
  - curl=7.80.0
  - cvxopt=1.2.7
  - cvxpy=1.1.17
  - cvxpy-base=1.1.17
  - cycler=0.11.0
  - dill=0.3.4
  - dsdp=5.8
  - ecos=2.0.8
  - fftw=3.3.10
  - freetype=2.10.4
  - glpk=4.65
  - gmp=6.2.1
  - gsl=2.7
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=67.1
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - ipopt=3.14.4
  - jax=0.2.25
  - jaxlib=0.1.73
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libzip=1.8.0
  - libzlib=1.2.11
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - metis=5.1.0
  - mosek=9.3.10
  - mpfr=4.1.0
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - ncurses=6.2
  - netcdf4=1.5.8
  - numpy=1.21.4
  - numpyro=0.8.0
  - openssl=3.0.0
  - opt_einsum=3.3.0
  - osqp=0.6.2.post0
  - packaging=21.3
  - pandas=1.3.4
  - pip=21.3.1
  - pyparsing=3.0.6
  - pyscipopt=3.4.0
  - pyshp=2.1.3
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.8
  - pytz=2021.3
  - qdldl-python=0.1.5
  - readline=8.1
  - scikit-learn=1.0.1
  - scip=7.0.3
  - scipy=1.7.2
  - scotch=6.0.9
  - scs=3.0.0
  - setuptools=59.1.1
  - six=1.16.0
  - sqlite=3.36.0
  - suitesparse=5.10.1
  - tbb=2020.2
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - typing_extensions=4.0.0
  - wheel=0.37.0
  - xarray=0.20.1
  - xz=5.2.5
  - zipp=3.6.0
  - zlib=1.2.11
